name: Dry run

on:
  workflow_dispatch:
  pull_request:

jobs:
  msync-noop:
    name: Run msync --noop against all modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true

      - name: Run msync --noop
        run: bundle exec msync update --noop --git-base=https://github.com/ --branch noop
